# Generated by Django 4.1.7 on 2023-02-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("function", models.CharField(max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FunctionParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("value", models.FloatField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date published"
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="functions.function",
                    ),
                ),
            ],
        ),
    ]
